package application.actors;

public enum NPCDefaultStats {
	
	//Demon
	DEMON_DEFAULT_INITIAL_STRENGTH_POINTS(1.3f, "Strength Points"),
	DEMON_DEFAULT_INITIAL_INTELLIGENCE_POINTS(0.3f, "Intelligence Points"),
	DEMON_DEFAULT_INITIAL_DEXTIRITY_POINTS(2.0f, "Dextirity Points"),
	DEMON_DEFAULT_INITIAL_HEALTH_POINTS(13.5f, "Health Points"),
	
	DEMON_DEFAULT_INITIAL_STRENGTH_POINTS_SCALING(1.3f, "Strength Scale"),
	DEMON_DEFAULT_INITIAL_INTELLIGENCE_POINTS_SCALING(0.7f, "Intelligence Scale"),
	DEMON_DEFAULT_INITIAL_DEXTIRITY_POINTS_SCALING(3.7f, "Dextirity Scale"),
	DEMON_DEFAULT_INITIAL_HEALTH_POINTS_SCALING(9.0f, "Health Scale"),
	
	//Necromancer
	NECROMANCER_DEFAULT_INITIAL_STRENGTH_POINTS(1.0f, "Strength Points"),
	NECROMANCER_DEFAULT_INITIAL_INTELLIGENCE_POINTS(2.2f, "Intelligence Points"),
	NECROMANCER_DEFAULT_INITIAL_DEXTIRITY_POINTS(0.4f, "Dextirity Points"),
	NECROMANCER_DEFAULT_INITIAL_HEALTH_POINTS(10.2f, "Health Points"),
	
	NECROMANCER_DEFAULT_INITIAL_STRENGTH_POINTS_SCALING(0.3f, "Strength Scale"),
	NECROMANCER_DEFAULT_INITIAL_INTELLIGENCE_POINTS_SCALING(5.1f, "Intelligence Scale"),
	NECROMANCER_DEFAULT_INITIAL_DEXTIRITY_POINTS_SCALING(0.3f, "Dextirity Scale"),
	NECROMANCER_DEFAULT_INITIAL_HEALTH_POINTS_SCALING(5.0f, "Health Scale"),
	
	//Ancient
	ANCIENT_DEFAULT_INITIAL_STRENGTH_POINTS(3.0f, "Strength Points"),
	ANCIENT_DEFAULT_INITIAL_INTELLIGENCE_POINTS(3.0f, "Intelligence Points"),
	ANCIENT_DEFAULT_INITIAL_DEXTIRITY_POINTS(3.0f, "Dextirity Points"),
	ANCIENT_DEFAULT_INITIAL_HEALTH_POINTS(27.3f, "Health Points"),
	
	ANCIENT_DEFAULT_INITIAL_STRENGTH_POINTS_SCALING(10.0f, "Strength Scale"),
	ANCIENT_DEFAULT_INITIAL_INTELLIGENCE_POINTS_SCALING(10.0f, "Intelligence Scale"),
	ANCIENT_DEFAULT_INITIAL_DEXTIRITY_POINTS_SCALING(10.0f, "Dextirity Scale"),
	ANCIENT_DEFAULT_INITIAL_HEALTH_POINTS_SCALING(30.0f, "Health Scale"),
	
	//Guardian
	GUARDIAN_DEFAULT_INITIAL_STRENGTH_POINTS(1.3f, "Strength Points"),
	GUARDIAN_DEFAULT_INITIAL_INTELLIGENCE_POINTS(0.3f, "Intelligence Points"),
	GUARDIAN_DEFAULT_INITIAL_DEXTIRITY_POINTS(2.0f, "Dextirity Points"),
	GUARDIAN_DEFAULT_INITIAL_HEALTH_POINTS(13.5f, "Health Points"),
	
	GUARDIAN_DEFAULT_INITIAL_STRENGTH_POINTS_SCALING(1.3f, "Strength Scale"),
	GUARDIAN_DEFAULT_INITIAL_INTELLIGENCE_POINTS_SCALING(0.7f, "Intelligence Scale"),
	GUARDIAN_DEFAULT_INITIAL_DEXTIRITY_POINTS_SCALING(3.7f, "Dextirity Scale"),
	GUARDIAN_DEFAULT_INITIAL_HEALTH_POINTS_SCALING(9.0f, "Health Scale"),
	
	//Priest
	PRIEST_DEFAULT_INITIAL_STRENGTH_POINTS(1.0f, "Strength Points"),
	PRIEST_DEFAULT_INITIAL_INTELLIGENCE_POINTS(2.2f, "Intelligence Points"),
	PRIEST_DEFAULT_INITIAL_DEXTIRITY_POINTS(0.4f, "Dextirity Points"),
	PRIEST_DEFAULT_INITIAL_HEALTH_POINTS(10.2f, "Health Points"),
	
	PRIEST_DEFAULT_INITIAL_STRENGTH_POINTS_SCALING(0.3f, "Strength Scale"),
	PRIEST_DEFAULT_INITIAL_INTELLIGENCE_POINTS_SCALING(5.1f, "Intelligence Scale"),
	PRIEST_DEFAULT_INITIAL_DEXTIRITY_POINTS_SCALING(0.3f, "Dextirity Scale"),
	PRIEST_DEFAULT_INITIAL_HEALTH_POINTS_SCALING(5.0f, "Health Scale"),
	
	//Elite
	ELITE_DEFAULT_INITIAL_STRENGTH_POINTS(3.0f, "Strength Points"),
	ELITE_DEFAULT_INITIAL_INTELLIGENCE_POINTS(3.0f, "Intelligence Points"),
	ELITE_DEFAULT_INITIAL_DEXTIRITY_POINTS(3.0f, "Dextirity Points"),
	ELITE_DEFAULT_INITIAL_HEALTH_POINTS(27.3f, "Health Points"),
	
	ELITE_DEFAULT_INITIAL_STRENGTH_POINTS_SCALING(10.0f, "Strength Scale"),
	ELITE_DEFAULT_INITIAL_INTELLIGENCE_POINTS_SCALING(10.0f, "Intelligence Scale"),
	ELITE_DEFAULT_INITIAL_DEXTIRITY_POINTS_SCALING(10.0f, "Dextirity Scale"),
	ELITE_DEFAULT_INITIAL_HEALTH_POINTS_SCALING(30.0f, "Health Scale");
	
	public final float value;
	public final String info;
	
	private NPCDefaultStats(float value, String info) {
		this.value = value;
		this.info = info;
	}
	
}
